// ============================================================
// PSLE RevisionPro — Explanation Generator
// Calls Claude API to write a teaching explanation for every
// question, then outputs an SQL file to load into Supabase.
//
// Run with:
//   ANTHROPIC_API_KEY=your_key node generate_explanations.js
//
// Requires: npm install @anthropic-ai/sdk
// ============================================================

import Anthropic from '@anthropic-ai/sdk'
import { readFileSync, writeFileSync } from 'fs'

const API_KEY = process.env.ANTHROPIC_API_KEY
if (!API_KEY) {
  console.error('❌  Set ANTHROPIC_API_KEY environment variable')
  process.exit(1)
}

const client = new Anthropic({ apiKey: API_KEY })

// ── Load questions ────────────────────────────────────────────
const data = JSON.parse(readFileSync('./psle_science_questions_enriched.json', 'utf-8'))
const questions = data.questions

// ── Generate one explanation ──────────────────────────────────
async function generateExplanation(q) {
  const correctOption = q.options.find(o => o.letter === q.correct_answer)
  const correctText   = correctOption?.text ?? q.correct_answer

  const wrongOptions = q.options
    .filter(o => o.letter !== q.correct_answer)
    .map(o => `${o.letter}. ${o.text}`)
    .join(', ')

  const prompt = `You are a science teacher writing explanations for Standard 6 PSLE students in Botswana (age 11-13).

Question: ${q.question_text}
${q.context_text ? `Context: ${q.context_text}` : ''}
Correct answer: ${q.correct_answer}. ${correctText}
Wrong options: ${wrongOptions}
Topic: ${q.subject_area}
Curriculum code: ${q.curriculum_code || 'N/A'}

Write a clear, encouraging explanation (2-3 sentences max) that:
1. Confirms WHY the correct answer is right
2. Briefly explains why the most tempting wrong answer is incorrect (if obvious)
3. Uses simple language suitable for a 12-year-old in Botswana
4. Does NOT start with "The correct answer is..." — start with the concept itself

Return ONLY the explanation text. No labels, no quotes, no markdown.`

  const response = await client.messages.create({
    model: 'claude-sonnet-4-5',
    max_tokens: 200,
    messages: [{ role: 'user', content: prompt }]
  })

  return response.content[0].text.trim()
}

// ── Process in batches ────────────────────────────────────────
const BATCH_SIZE = 5
const DELAY_MS   = 4000   // be gentle on the API

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms))
}

async function main() {
  console.log(`🚀  Generating explanations for ${questions.length} questions`)
  console.log(`   Batch size: ${BATCH_SIZE} | Estimated time: ~${Math.ceil(questions.length / BATCH_SIZE * 2)} minutes\n`)

  const results = []
  let success = 0
  let failed  = 0

  for (let i = 0; i < questions.length; i += BATCH_SIZE) {
    const batch = questions.slice(i, i + BATCH_SIZE)

    const batchResults = await Promise.all(
      batch.map(async q => {
        try {
          const explanation = await generateExplanation(q)
          return { id: q.id, explanation, ok: true }
        } catch (err) {
          console.error(`  ⚠️  Failed Q${q.question_number} (${q.paper_id}): ${err.message}`)
          return { id: q.id, explanation: null, ok: false }
        }
      })
    )

    results.push(...batchResults)
    success += batchResults.filter(r => r.ok).length
    failed  += batchResults.filter(r => !r.ok).length

    const done = Math.min(i + BATCH_SIZE, questions.length)
    process.stdout.write(`   ${done}/${questions.length} — ${success} ok, ${failed} failed\r`)

    if (i + BATCH_SIZE < questions.length) await sleep(DELAY_MS)
  }

  console.log(`\n\n✅  Done — ${success} explanations generated, ${failed} failed`)

  // ── Write SQL update script ───────────────────────────────
  const lines = [
    '-- ============================================================',
    '-- PSLE RevisionPro — Explanation UPDATE Script',
    '-- Auto-generated by generate_explanations.js',
    '-- Run in Supabase SQL Editor',
    '-- ============================================================',
    '',
    '-- Step 1: Add explanation column if it does not exist',
    `DO $$`,
    `BEGIN`,
    `  IF NOT EXISTS (`,
    `    SELECT 1 FROM information_schema.columns`,
    `    WHERE table_name='questions' AND column_name='explanation'`,
    `  ) THEN`,
    `    ALTER TABLE questions ADD COLUMN explanation TEXT;`,
    `  END IF;`,
    `END $$;`,
    '',
    'BEGIN;',
    '',
  ]

  for (const r of results) {
    if (!r.ok || !r.explanation) continue
    // Escape single quotes for SQL
    const escaped = r.explanation.replace(/'/g, "''")
    lines.push(`UPDATE questions SET explanation = '${escaped}' WHERE id = '${r.id}';`)
  }

  lines.push('')
  lines.push('COMMIT;')
  lines.push(`-- ${success} explanations loaded`)

  writeFileSync('./update_explanations.sql', lines.join('\n'))
  console.log(`📄  SQL file written: update_explanations.sql`)

  // ── Also update the JSON ──────────────────────────────────
  const explanationMap = Object.fromEntries(results.filter(r => r.ok).map(r => [r.id, r.explanation]))
  for (const q of data.questions) {
    if (explanationMap[q.id]) q.explanation = explanationMap[q.id]
  }
  writeFileSync('./psle_science_questions_enriched.json', JSON.stringify(data, null, 2))
  console.log(`📄  JSON updated with explanations`)

  console.log(`\n🎉  Next step: run update_explanations.sql in Supabase SQL Editor\n`)
}

main().catch(err => {
  console.error('\n❌  Fatal error:', err.message)
  process.exit(1)
})
